### ISSUE TITLE
why did you use GIT_SSL_NO_VERIFY

### ISSUE THREAD

**Issue by salmanishere** [ebrahimraeyat/civilTools#16]
Can I ask, why you used `'GIT_SSL_NO_VERIFY': '1'` in the *civiltools.py* ? It is not secure.

**Comment by ebrahimraeyat** [comment]
when i wanted to create win32 version, it gives me error at update. I add this key to skip ssl check.

**Comment by salmanishere** [comment]
Would you please paste the error here? I have no windows machine so I cannot check the error if we let git check the ssl.

**Comment by ebrahimraeyat** [comment]
do you live in iran? if no, with which software you are doing your calculation? i mean software like etabs or safe.

**Comment by ebrahimraeyat** [comment]
this is error:

`Traceback (most recent call last):
  File "C:\Users\hossein\AppData\Local\civiltools\pkgs\civilTools\civiltools.py"
, line 89, in git_updates
    smsg = g.pull()
  File "C:\Users\hossein\AppData\Local\civiltools\pkgs\git\cmd.py", line 548, in
 <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Users\hossein\AppData\Local\civiltools\pkgs\git\cmd.py", line 1014, i
n _call_process
    return self.execute(call, **exec_kwargs)
  File "C:\Users\hossein\AppData\Local\civiltools\pkgs\git\cmd.py", line 825, in
 execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull
  stderr: 'fatal: unable to access 'https://github.com/ebrahimraeyat/civilTools.
git/': SSL certificate problem: certificate is not yet valid

`

**Comment by salmanishere** [comment]
I guess the problem comes from the incorrect date on the computer. Is the date set correctly? 

You can also sync it with your code but I don't recommend it.
